### PR TITLE
Preserve fuzzy Flag when merging entries

### PR DESCRIPTION
**Pull request by maennchen**
Fix for #282

### CODE REVIEW

**Comment by josevalim** [comment]
I *think* this looks good to me. The only flags we support are `fuzzy` and `elixir-format` and it makes sense for us to merge both of them.

The only possible downside is if someone is using gettext for multiple languages and they accidentally mark some `elixir-format` with the invalid format, and now they can't rely on the merger to fix that for them. We could address this by unioning only the `fuzzy` flag, but I am not sure if this is worth it.

Thoughts @whatyouhide?

**Comment by maennchen** [comment]
@josevalim I was thinking about the elixir-format flag as well. I wasn't sure on how to deal with it.

If we do not want it included, I would suggest excluding it instead of only including fuzzy.

**Comment by whatyouhide** [comment]
@maennchen this makes sense to me conceptually. Can you check how GNU gettext behaves here? That's what I usually do when in doubt. `pomerge` to the rescue :) Let me know if you need help!

**Comment by whatyouhide** [comment]
@maennchen this makes sense to me conceptually. Can you check how GNU gettext behaves here? That's what I usually do when in doubt. `pomerge` to the rescue :) Let me know if you need help!

**Comment by maennchen** [comment]
@whatyouhide I'm not sure if I have it correct:

https://github.com/winlibs/gettext/blob/master/source/gettext-tools/src/msgmerge.c#L1263

```c
  /* The flags are mixed in a special way.  Some informations come
     from the reference message (such as format/no-format), others
     come from the definition file (fuzzy or not).  */
  result->is_fuzzy = def->is_fuzzy | force_fuzzy;

  /* If ref and def have the same msgid but different msgid_plural, it's
     a reason to mark the result fuzzy.  */
  if (!result->is_fuzzy
      && (ref->msgid_plural != NULL
          ? def->msgid_plural == NULL
            || strcmp (ref->msgid_plural, def->msgid_plural) != 0
          : def->msgid_plural != NULL))
    result->is_fuzzy = true;
```

I would conclude from seeing that, that we should only union the fuzzy flag. Do you agree?

**Comment by josevalim** [comment]
Yeah, definitely. But they are treating the fuzzy flag specially, so perhaps we should do the same. :)

**Comment by maennchen** [comment]
@josevalim I'll update the PR accordingly.

**Comment by maennchen** [comment]
@josevalim I added a commit.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by whatyouhide** [comment]
Nice, thanks @josevalim and @maennchen! 💟

**Pull request merged**
