### PR TITLE
Preserve whitespaces in flags

### PR DESCRIPTION
**Pull request by lexmag**
See https://github.com/elixir-gettext/gettext/commit/bdd7aff1b9a1088af0131b2c30143621b7f1941d#r35590050.

What do you think about this approach?

### CODE REVIEW

**Comment by whatyouhide** [comment]
Yeah let's go with warning if whitespace is found and autofix like we do today. Thanks @lexmag!

**Comment by whatyouhide** [comment]
Btw @lexmag, waiting for the PR to not be in the draft state before reviewing/merging 🙃

**Comment by lexmag** [comment]
I've tried several more combinations of flags that contain space and can confirm that both Loco (https://localise.biz) and Transifex.com (transifex.com) parse `#, a b, c` to `["a b", "c"]`.
I think we better to do the same and keep whitespaced flags intact.
I wonder what do we actually get from auto-fixing? What are those tools that have originally influenced our choice?
In fact, if we preserve whitespaces we perhaps can skip the warning altogether (maybe add later if needed).

**Comment by whatyouhide** [comment]
@lexmag I see what you mean now. Yeah, if those tools only split on the comma, let's do the same.

**Comment by lexmag** [comment]
@whatyouhide thanks. Updated.

**Comment by whatyouhide** [comment]
Thanks @lexmag! ❤️❤️❤️

**Pull request merged**
